name: Continious Integration
on: push

jobs:
  bump-packagist:
    name: Send an update trigger to packagist
    runs-on: ubuntu-latest
    steps:
      - name: Sends update trigger to packagist
        env:
          PACKAGIST_API_KEY: ${{ secrets.PACKAGIST_API_KEY }}
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
        run: curl -XPOST -H'content-type:application/json' "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_API_KEY}" -d'{"repository":{"url":"https://packagist.org/packages/madewithlove/htaccess-cli"}}'

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse

  run:
    name: Run current version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: composer install -n --prefer-dist
    - name: Add a very basic htaccess file
      run: echo "RewriteRule .* /foo" >> .htaccess
    - name: Run current version of htaccess cli
      run: bin/htaccess https://example.com
