name: Continious Integration
on: push

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer
    - name: Install dependencies
      run: composer update -n --prefer-dist
    - name: PHPStan
      run: vendor/bin/phpstan analyse

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1']
        prefer-lowest: ['', '--prefer-lowest']
    steps:
    - uses: actions/checkout@master
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: pcov
        tools: composer
    - name: Install dependencies
      if: matrix.php-versions != '8.1'
      run: composer update -n --prefer-dist ${{ matrix.prefer-lowest }}
    - name: Install dependencies
      if: matrix.php-versions == '8.1'
      run: composer install -n --prefer-dist --ignore-platform-req=php
    - name: Run PHPUnit unit tests
      run: vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: matrix.php-versions == '8.0'

  run:
    name: Run current version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: composer install -n --prefer-dist
    - name: Add a very basic htaccess file
      run: echo "RewriteRule .* /foo" >> .htaccess
    - name: Run current version of htaccess cli
      run: bin/htaccess https://example.com
