name: Continious Integration

on:
  push
#  push:
#    tags:
#      - 'v*'

jobs:
  docker-publish:
    name: Publish new tag to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Do a docker login
        env:
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
        run: docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PASS}
      - name: Get version name
        id: get_version
        run: echo ::set-output name=version::$(echo ${GITHUB_REF##*/} | cut -c2-)
      - name: output version name
        run: echo ${{ steps.get_version.outputs.version }}
